# Generated by Django 4.0.4 on 2022-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('hieght', models.PositiveIntegerField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('gender', models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')], null=True)),
                ('ap_hi', models.PositiveIntegerField(null=True)),
                ('ap_lo', models.PositiveIntegerField(null=True)),
                ('cholesterol', models.PositiveIntegerField(choices=[(1, 'normal'), (2, 'above normal'), (3, 'well above normal')], null=True)),
                ('gluc', models.PositiveIntegerField(choices=[(1, 'normal'), (2, 'above normal'), (3, 'well above normal')], null=True)),
                ('smoking', models.PositiveIntegerField(choices=[(0, 'True'), (1, 'False')], null=True)),
                ('alco', models.PositiveIntegerField(choices=[(0, 'True'), (1, 'False')], null=True)),
                ('active', models.PositiveIntegerField(choices=[(0, 'True'), (1, 'False')], null=True)),
                ('cardio', models.PositiveIntegerField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
