# Generated by Django 4.0.4 on 2022-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='active',
            field=models.PositiveIntegerField(choices=[(1, 'YES'), (0, 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='alco',
            field=models.PositiveIntegerField(choices=[(1, 'YES'), (0, 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='smoking',
            field=models.PositiveIntegerField(choices=[(1, 'YES'), (0, 'NO')], null=True),
        ),
    ]
