# Generated by Django 4.0.4 on 2022-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardio', '0002_alter_data_active_alter_data_alco_alter_data_smoking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='cardio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
