# Generated by Django 4.0.4 on 2022-05-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardio', '0003_alter_data_cardio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Female'), (2, 'Male')], null=True),
        ),
    ]
