# Generated by Django 4.0.4 on 2022-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardio', '0004_alter_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='active',
            field=models.PositiveIntegerField(choices=[(1, 'YES'), (0, 'NO')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='alco',
            field=models.PositiveIntegerField(choices=[(1, 'YES'), (0, 'NO')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='ap_hi',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='ap_lo',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='cholesterol',
            field=models.PositiveIntegerField(choices=[(1, 'normal'), (2, 'above normal'), (3, 'well above normal')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Female'), (2, 'Male')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='gluc',
            field=models.PositiveIntegerField(choices=[(1, 'normal'), (2, 'above normal'), (3, 'well above normal')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='hieght',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='smoking',
            field=models.PositiveIntegerField(choices=[(1, 'YES'), (0, 'NO')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
